export const CLOSE_SIDEDRAWER = 'CLOSE_SIDEDRAWER';

export const OPEN_SERVICES = 'OPEN_SERVICES';
export const OPEN_TESTIMONIAL = 'OPEN_TESTIMONIAL';
export const OPEN_STORE = 'OPEN_STORE';

export const OPEN_CREDITS = 'OPEN_CREDITS';
export const CLOSE_CREDITS = 'CLOSE_CREDITS';