export const CLOSE_SIDEDRAWER = 'CLOSE_SIDEDRAWER';

export const OPEN_ABOUT = 'OPEN_ABOUT';
export const OPEN_TESTIMONIAL = 'OPEN_TESTIMONIAL';
export const OPEN_STORE = 'OPEN_STORE';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';

export const OPEN_CREDITS_MODAL = 'OPEN_CREDITS_MODAL';
export const CLOSE_CREDITS_MODAL = 'CLOSE_CREDITS_MODAL';